In [1]:
import numpy as np

### Exercício 1.1.11
##### Sendo A uma matriz, calcule alguns membros da sequência ${A}$, ${A}^{2}$ , ${...}$ , ${A}^{k}$

- (a) $
\begin{gather}
    A =
    \begin{bmatrix}
        1 & 1/2 \\
        0 & 1/3 
    \end{bmatrix}
\end{gather}
$ 

- (b) $
\begin{gather}
    B =
    \begin{bmatrix}
        1/2 & 1/3 \\
        0 & -1/5 
    \end{bmatrix}
\end{gather}
$

In [140]:
A = np.array([[1, 1./2], 
             [0, 1./3]])
A_exponentiated = np.linalg.matrix_power(A, 1000)
A_exponentiated

array([[1.  , 0.75],
       [0.  , 0.  ]])

In [146]:
B = np.array([[1./2, 1/3], 
             [0, -1./5]])
B_exponentiated = np.linalg.matrix_power(B, 2000)
B_exponentiated

array([[0., 0.],
       [0., 0.]])

### Exercício 1.1.12
###### Calcule as potências das matrizes dadas a seguir e encontre experimentalmente (por tentativa!) o menor inteiro k > 1 tal que

- (a) 
$
\begin{gather}
    {A}^{k} = I_3, {A} =
    \begin{bmatrix}
        0 & 0 & 1 \\
        1 & 0 & 0 \\
        0 & 1 & 0
    \end{bmatrix}
\end{gather}
$ 

- (b) 
$
\begin{gather}
    {A}^{k} = I_4, {A} =
    \begin{bmatrix}
        0 & 1 & 0 & 0 \\
        -1 & 0 & 0 & 0 \\
        0 & 0 & 0 & 1 \\
        0 & 0 & 1 & 0
    \end{bmatrix}
\end{gather}
$

- (c)
$
\begin{gather}
    {A}^{k} = {0}, {A} =
    \begin{bmatrix}
        0 & 1 & 0 & 0 \\
        0 & 0 & 1 & 0 \\
        0 & 0 & 0 & 1 \\
        0 & 0 & 0 & 0
    \end{bmatrix}
\end{gather}
$

In [41]:
# 1.1.12 (a)
A = np.array([[0, 0, 1],
              [1, 0, 0],
             [0, 1, 0]])

In [49]:
A_exponentiated = np.linalg.matrix_power(A, 3)
A_exponentiated

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [50]:
# 1.1.12 (b)
A = np.array([[0, 1, 0, 0],
              [-1, 0, 0, 0],
             [0, 0, 0, 1],
             [0, 0, 1, 0]])

In [53]:
A_exponentiated = np.linalg.matrix_power(A, 4)
A_exponentiated

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [68]:
# 1.1.12 (c)
A = np.array([[0, 1, 0, 0],
              [0, 0, 1, 0],
             [0, 0, 0, 1],
             [0, 0, 0, 0]])

In [70]:
A_exponentiated = np.linalg.matrix_power(A, 4)
A_exponentiated

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

### Exercício 1.1.13
###### Vamos fazer um experimento para tentar ter uma ideia do quão comum é encontrar matrizes cujo produto comuta.

In [89]:
# 1.1.13
count = 0
for i in range(1000):
    A = np.random.randint(2, size = (3,3))
    B = np.random.randint(2, size = (3,3))
    if np.array_equal(np.dot(A,B), np.dot(B,A)):
        count += 1
count

21

### Exercício 1.1.14
###### Faça um experimento semelhante ao anterior, mas para o caso em que cada uma das matrizes é diagonal, isto é, os elementos que estão fora da diagonal são iguais a zero.

In [102]:
# 1.1.14
count = 0
for i in range(1000):
    A = np.random.randint(10, size = (3,3))
    B = np.random.randint(10, size = (3,3))
    
    A = np.diag(np.diag(A))
    B = np.diag(np.diag(B))

    if np.array_equal(np.dot(A,B), np.dot(B,A)):
        count += 1
count

1000

### Exercício 1.1.15
###### Faça um experimento semelhante ao anterior, mas para o caso em que uma das matrizes é diagonal.

In [106]:
# 1.1.15
count = 0
for i in range(1000):
    A = np.random.randint(10, size = (3,3))
    B = np.random.randint(10, size = (3,3))
    
    A = np.diag(np.diag(A))

    if np.array_equal(np.dot(A,B), np.dot(B,A)):
        count += 1
count

11